#!/bin/sh

iPATH="$1"

t=`/usr/bin/stat -c %Y "$1"`

if getfattr --absolute-names  -d "$1" 2>/dev/null | fgrep -q "user.adler_mtime=\"$t\""; then
  if getfattr --absolute-names -d "$1" -n user.adler_value | fgrep -q "user.adler_value"; then
     getfattr --absolute-names -d "$1" -n user.adler_value | sed -n -e 's/^user.adler_value="\([0-9a-f]*\)"/\1/p'
    exit 0
  fi
fi




adler=`python -c 'import zlib;import sys
s=1L
while True:
 r=sys.stdin.read(65536)
 s=zlib.adler32(r,s) & 0xffffffff
 if len(r) != 65536:
   print "%x" % s
   raise SystemExit' < "$iPATH"`


# arcls leftpads with 0s to get even numbers (bytes)


adler=`printf "%8s" "$adler" | sed -e 's/ /0/g'`

echo $adler

setfattr -n user.adler_mtime -v "$t" "$iPATH" 2>/dev/null
setfattr -n user.adler_value -v "$adler" "$iPATH" 2>/dev/null
